#!/usr/bin/env python3
"""Plan the M4a multi-device shard split and emit a verifiable move script.

Assigns each *.safetensors shard of a model directory to one of several
devices so that expected bytes per device are proportional to device
bandwidth, using greedy argmin(assigned_bytes / weight) over shards in sorted
filename order. Sorted-order greedy interleaves devices, which matters because
one sparse layer's experts span only ~1.8 adjacent shards: adjacent shards on
different devices means a layer's reads run on different spindles in parallel.

The device named `keep` is the filesystem the model dir already lives on: its
shards are not moved, but they count toward its assigned bytes.

Usage:
  scripts/plan-shard-split.py <model-dir> keep=<weight> \
      <name>=<mountpoint>:<weight> [...] --out <plan-dir>

Example (weights = measured GB/s):
  scripts/plan-shard-split.py ~/models/GLM-5.2-colibri-int4-with-int8-mtp \
      keep=1.12 stripe=/srv/modelstripe:1.00 600p=/srv/model600p:0.77 \
      --out bench-data/2026-08-XX-M4a-split

Emits <plan-dir>/plan.tsv and <plan-dir>/move.sh. move.sh is restartable: it
skips shards whose symlink already points at a verified copy. Originals go to
<model-dir>/.trash-presplit/ and are NOT deleted; delete by hand only after a
successful model load plus reference-transcript byte-compare.
"""
import argparse
import os
import stat
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("model_dir")
    ap.add_argument("targets", nargs="+", help="keep=W or name=path:W")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    devices = []  # (name, path-or-None, weight)
    for spec in a.targets:
        name, _, rest = spec.partition("=")
        if name == "keep":
            devices.append(("keep", None, float(rest)))
        else:
            path, _, w = rest.rpartition(":")
            if not path or not w:
                sys.exit(f"bad target spec {spec!r} (want name=path:weight)")
            devices.append((name, path, float(w)))
    if not any(d[0] == "keep" for d in devices):
        sys.exit("need a keep=<weight> target for the current filesystem")
    for name, path, _ in devices:
        if path is not None and not os.path.isdir(path):
            sys.exit(f"target {name}: {path} is not a directory (mounted?)")

    mdir = os.path.abspath(a.model_dir)
    shards = sorted(
        f for f in os.listdir(mdir)
        if f.endswith(".safetensors")
        and stat.S_ISREG(os.lstat(os.path.join(mdir, f)).st_mode)
    )
    if not shards:
        sys.exit(f"no regular .safetensors shards in {mdir} (already split?)")

    sizes = {f: os.path.getsize(os.path.join(mdir, f)) for f in shards}
    assigned = {name: 0 for name, _, _ in devices}
    where = {}
    for f in shards:
        name = min(devices, key=lambda d: assigned[d[0]] / d[2])[0]
        where[f] = name
        assigned[name] += sizes[f]

    os.makedirs(a.out, exist_ok=True)
    total = sum(sizes.values())
    with open(os.path.join(a.out, "plan.tsv"), "w") as fh:
        fh.write("shard\tbytes\tdevice\n")
        for f in shards:
            fh.write(f"{f}\t{sizes[f]}\t{where[f]}\n")
    print(f"{len(shards)} shards, {total / 1e9:.1f} GB")
    wsum = sum(w for _, _, w in devices)
    for name, path, w in devices:
        got = assigned[name]
        print(
            f"  {name:8s} {got / 1e9:7.1f} GB  ({got / total:5.1%} vs"
            f" bandwidth share {w / wsum:5.1%})  -> {path or '(stays)'}"
        )

    mv = os.path.join(a.out, "move.sh")
    with open(mv, "w") as fh:
        fh.write("#!/usr/bin/env bash\n")
        fh.write("# Generated by plan-shard-split.py — cp, verify, swap symlink.\n")
        fh.write("# Restartable; originals kept in .trash-presplit/ until the\n")
        fh.write("# model-load + reference-transcript gate passes.\n")
        fh.write("set -euo pipefail\n")
        fh.write(f"MDIR={mdir!r}\n")
        fh.write('mkdir -p "$MDIR/.trash-presplit"\n')
        for name, path, _ in devices:
            if path is None:
                continue
            sub = os.path.join(path, os.path.basename(mdir))
            fh.write(f"mkdir -p {sub!r}\n")
        for f in shards:
            name = where[f]
            path = dict((n, p) for n, p, _ in devices)[name]
            if path is None:
                continue
            dst = os.path.join(path, os.path.basename(mdir), f)
            fh.write(
                f'if [ ! -L "$MDIR"/{f} ]; then\n'
                f"  echo '-- {f} -> {name}'\n"
                f'  cp "$MDIR"/{f} {dst!r}.part\n'
                f'  a=$(sha256sum < "$MDIR"/{f}); b=$(sha256sum < {dst!r}.part)\n'
                f'  [ "$a" = "$b" ] || {{ echo "!! checksum mismatch {f}"; exit 1; }}\n'
                f'  mv {dst!r}.part {dst!r}\n'
                f'  mv "$MDIR"/{f} "$MDIR"/.trash-presplit/{f}\n'
                f'  ln -sfn {dst!r} "$MDIR"/{f}\n'
                f"fi\n"
            )
        fh.write('echo "all moves verified; originals in $MDIR/.trash-presplit"\n')
    os.chmod(mv, 0o755)
    print(f"wrote {mv}")


if __name__ == "__main__":
    main()
